/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyPermitsRouteImport } from './routes/my-permits'
import { Route as MyCompetitionsRouteImport } from './routes/my-competitions'
import { Route as MyCardRouteImport } from './routes/my-card'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GraduatesRouteImport } from './routes/graduates'
import { Route as DiplomaRequestRouteImport } from './routes/diploma-request'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChampionshipsRouteImport } from './routes/championships'
import { Route as BlackBeltsRouteImport } from './routes/black-belts'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademiesRouteImport } from './routes/academies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyAthleteIdRouteImport } from './routes/verify.$athleteId'
import { Route as RegisterAthleteRouteImport } from './routes/register.athlete'
import { Route as RegisterAcademyRouteImport } from './routes/register.academy'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as MyPermitPermitNumberRouteImport } from './routes/my-permit.$permitNumber'
import { Route as GraduatesGraduateIdRouteImport } from './routes/graduates.$graduateId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as BlackBeltsIdRouteImport } from './routes/black-belts.$id'
import { Route as AthleteSignupRouteImport } from './routes/athlete.signup'
import { Route as AthleteResetPasswordRouteImport } from './routes/athlete.reset-password'
import { Route as AthleteLoginRouteImport } from './routes/athlete.login'
import { Route as AthleteForgotPasswordRouteImport } from './routes/athlete.forgot-password'
import { Route as AdminYoutubeRouteImport } from './routes/admin.youtube'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminRankingsRouteImport } from './routes/admin.rankings'
import { Route as AdminPermitsRouteImport } from './routes/admin.permits'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDiplomaRequestsRouteImport } from './routes/admin.diploma-requests'
import { Route as AdminBlackBeltsRouteImport } from './routes/admin.black-belts'
import { Route as AdminBenefitsRouteImport } from './routes/admin.benefits'
import { Route as AdminAthletesRouteImport } from './routes/admin.athletes'
import { Route as AdminAcademiesRouteImport } from './routes/admin.academies'
import { Route as AcademyPermitRouteImport } from './routes/academy.permit'
import { Route as VerifyAcademyPermitNumberRouteImport } from './routes/verify.academy.$permitNumber'
import { Route as RegisterEventEventIdRouteImport } from './routes/register.event.$eventId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPermitsRoute = MyPermitsRouteImport.update({
  id: '/my-permits',
  path: '/my-permits',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompetitionsRoute = MyCompetitionsRouteImport.update({
  id: '/my-competitions',
  path: '/my-competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCardRoute = MyCardRouteImport.update({
  id: '/my-card',
  path: '/my-card',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesRoute = GraduatesRouteImport.update({
  id: '/graduates',
  path: '/graduates',
  getParentRoute: () => rootRouteImport,
} as any)
const DiplomaRequestRoute = DiplomaRequestRouteImport.update({
  id: '/diploma-request',
  path: '/diploma-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipsRoute = ChampionshipsRouteImport.update({
  id: '/championships',
  path: '/championships',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackBeltsRoute = BlackBeltsRouteImport.update({
  id: '/black-belts',
  path: '/black-belts',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesRoute = AcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyAthleteIdRoute = VerifyAthleteIdRouteImport.update({
  id: '/verify/$athleteId',
  path: '/verify/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAthleteRoute = RegisterAthleteRouteImport.update({
  id: '/register/athlete',
  path: '/register/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAcademyRoute = RegisterAcademyRouteImport.update({
  id: '/register/academy',
  path: '/register/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPermitPermitNumberRoute = MyPermitPermitNumberRouteImport.update({
  id: '/my-permit/$permitNumber',
  path: '/my-permit/$permitNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesGraduateIdRoute = GraduatesGraduateIdRouteImport.update({
  id: '/$graduateId',
  path: '/$graduateId',
  getParentRoute: () => GraduatesRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackBeltsIdRoute = BlackBeltsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlackBeltsRoute,
} as any)
const AthleteSignupRoute = AthleteSignupRouteImport.update({
  id: '/athlete/signup',
  path: '/athlete/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteResetPasswordRoute = AthleteResetPasswordRouteImport.update({
  id: '/athlete/reset-password',
  path: '/athlete/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteLoginRoute = AthleteLoginRouteImport.update({
  id: '/athlete/login',
  path: '/athlete/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteForgotPasswordRoute = AthleteForgotPasswordRouteImport.update({
  id: '/athlete/forgot-password',
  path: '/athlete/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingsRoute = AdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermitsRoute = AdminPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiplomaRequestsRoute = AdminDiplomaRequestsRouteImport.update({
  id: '/diploma-requests',
  path: '/diploma-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlackBeltsRoute = AdminBlackBeltsRouteImport.update({
  id: '/black-belts',
  path: '/black-belts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBenefitsRoute = AdminBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAthletesRoute = AdminAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademiesRoute = AdminAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => AdminRoute,
} as any)
const AcademyPermitRoute = AcademyPermitRouteImport.update({
  id: '/academy/permit',
  path: '/academy/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAcademyPermitNumberRoute =
  VerifyAcademyPermitNumberRouteImport.update({
    id: '/verify/academy/$permitNumber',
    path: '/verify/academy/$permitNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterEventEventIdRoute = RegisterEventEventIdRouteImport.update({
  id: '/register/event/$eventId',
  path: '/register/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/athletes': typeof AthletesRoute
  '/benefits': typeof BenefitsRoute
  '/black-belts': typeof BlackBeltsRouteWithChildren
  '/championships': typeof ChampionshipsRoute
  '/contact': typeof ContactRoute
  '/diploma-request': typeof DiplomaRequestRoute
  '/graduates': typeof GraduatesRouteWithChildren
  '/members': typeof MembersRoute
  '/my-card': typeof MyCardRoute
  '/my-competitions': typeof MyCompetitionsRoute
  '/my-permits': typeof MyPermitsRoute
  '/my-profile': typeof MyProfileRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/typography': typeof TypographyRoute
  '/welcome': typeof WelcomeRoute
  '/academy/permit': typeof AcademyPermitRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/diploma-requests': typeof AdminDiplomaRequestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permits': typeof AdminPermitsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/athlete/forgot-password': typeof AthleteForgotPasswordRoute
  '/athlete/login': typeof AthleteLoginRoute
  '/athlete/reset-password': typeof AthleteResetPasswordRoute
  '/athlete/signup': typeof AthleteSignupRoute
  '/black-belts/$id': typeof BlackBeltsIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/my-permit/$permitNumber': typeof MyPermitPermitNumberRoute
  '/news/$slug': typeof NewsSlugRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/register/event/$eventId': typeof RegisterEventEventIdRoute
  '/verify/academy/$permitNumber': typeof VerifyAcademyPermitNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/athletes': typeof AthletesRoute
  '/benefits': typeof BenefitsRoute
  '/black-belts': typeof BlackBeltsRouteWithChildren
  '/championships': typeof ChampionshipsRoute
  '/contact': typeof ContactRoute
  '/diploma-request': typeof DiplomaRequestRoute
  '/graduates': typeof GraduatesRouteWithChildren
  '/members': typeof MembersRoute
  '/my-card': typeof MyCardRoute
  '/my-competitions': typeof MyCompetitionsRoute
  '/my-permits': typeof MyPermitsRoute
  '/my-profile': typeof MyProfileRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/typography': typeof TypographyRoute
  '/welcome': typeof WelcomeRoute
  '/academy/permit': typeof AcademyPermitRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/diploma-requests': typeof AdminDiplomaRequestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permits': typeof AdminPermitsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/athlete/forgot-password': typeof AthleteForgotPasswordRoute
  '/athlete/login': typeof AthleteLoginRoute
  '/athlete/reset-password': typeof AthleteResetPasswordRoute
  '/athlete/signup': typeof AthleteSignupRoute
  '/black-belts/$id': typeof BlackBeltsIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/my-permit/$permitNumber': typeof MyPermitPermitNumberRoute
  '/news/$slug': typeof NewsSlugRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/register/event/$eventId': typeof RegisterEventEventIdRoute
  '/verify/academy/$permitNumber': typeof VerifyAcademyPermitNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/athletes': typeof AthletesRoute
  '/benefits': typeof BenefitsRoute
  '/black-belts': typeof BlackBeltsRouteWithChildren
  '/championships': typeof ChampionshipsRoute
  '/contact': typeof ContactRoute
  '/diploma-request': typeof DiplomaRequestRoute
  '/graduates': typeof GraduatesRouteWithChildren
  '/members': typeof MembersRoute
  '/my-card': typeof MyCardRoute
  '/my-competitions': typeof MyCompetitionsRoute
  '/my-permits': typeof MyPermitsRoute
  '/my-profile': typeof MyProfileRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/typography': typeof TypographyRoute
  '/welcome': typeof WelcomeRoute
  '/academy/permit': typeof AcademyPermitRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/athletes': typeof AdminAthletesRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/diploma-requests': typeof AdminDiplomaRequestsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/permits': typeof AdminPermitsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/athlete/forgot-password': typeof AthleteForgotPasswordRoute
  '/athlete/login': typeof AthleteLoginRoute
  '/athlete/reset-password': typeof AthleteResetPasswordRoute
  '/athlete/signup': typeof AthleteSignupRoute
  '/black-belts/$id': typeof BlackBeltsIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/my-permit/$permitNumber': typeof MyPermitPermitNumberRoute
  '/news/$slug': typeof NewsSlugRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/register/event/$eventId': typeof RegisterEventEventIdRoute
  '/verify/academy/$permitNumber': typeof VerifyAcademyPermitNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academies'
    | '/admin'
    | '/athletes'
    | '/benefits'
    | '/black-belts'
    | '/championships'
    | '/contact'
    | '/diploma-request'
    | '/graduates'
    | '/members'
    | '/my-card'
    | '/my-competitions'
    | '/my-permits'
    | '/my-profile'
    | '/privacy'
    | '/rankings'
    | '/rules'
    | '/sitemap.xml'
    | '/terms'
    | '/typography'
    | '/welcome'
    | '/academy/permit'
    | '/admin/academies'
    | '/admin/athletes'
    | '/admin/benefits'
    | '/admin/black-belts'
    | '/admin/diploma-requests'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/permits'
    | '/admin/rankings'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/athlete/forgot-password'
    | '/athlete/login'
    | '/athlete/reset-password'
    | '/athlete/signup'
    | '/black-belts/$id'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/my-permit/$permitNumber'
    | '/news/$slug'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin/'
    | '/events/'
    | '/news/'
    | '/api/public/stripe-webhook'
    | '/register/event/$eventId'
    | '/verify/academy/$permitNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academies'
    | '/athletes'
    | '/benefits'
    | '/black-belts'
    | '/championships'
    | '/contact'
    | '/diploma-request'
    | '/graduates'
    | '/members'
    | '/my-card'
    | '/my-competitions'
    | '/my-permits'
    | '/my-profile'
    | '/privacy'
    | '/rankings'
    | '/rules'
    | '/sitemap.xml'
    | '/terms'
    | '/typography'
    | '/welcome'
    | '/academy/permit'
    | '/admin/academies'
    | '/admin/athletes'
    | '/admin/benefits'
    | '/admin/black-belts'
    | '/admin/diploma-requests'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/permits'
    | '/admin/rankings'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/athlete/forgot-password'
    | '/athlete/login'
    | '/athlete/reset-password'
    | '/athlete/signup'
    | '/black-belts/$id'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/my-permit/$permitNumber'
    | '/news/$slug'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin'
    | '/events'
    | '/news'
    | '/api/public/stripe-webhook'
    | '/register/event/$eventId'
    | '/verify/academy/$permitNumber'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academies'
    | '/admin'
    | '/athletes'
    | '/benefits'
    | '/black-belts'
    | '/championships'
    | '/contact'
    | '/diploma-request'
    | '/graduates'
    | '/members'
    | '/my-card'
    | '/my-competitions'
    | '/my-permits'
    | '/my-profile'
    | '/privacy'
    | '/rankings'
    | '/rules'
    | '/sitemap.xml'
    | '/terms'
    | '/typography'
    | '/welcome'
    | '/academy/permit'
    | '/admin/academies'
    | '/admin/athletes'
    | '/admin/benefits'
    | '/admin/black-belts'
    | '/admin/diploma-requests'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/permits'
    | '/admin/rankings'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/athlete/forgot-password'
    | '/athlete/login'
    | '/athlete/reset-password'
    | '/athlete/signup'
    | '/black-belts/$id'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/my-permit/$permitNumber'
    | '/news/$slug'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin/'
    | '/events/'
    | '/news/'
    | '/api/public/stripe-webhook'
    | '/register/event/$eventId'
    | '/verify/academy/$permitNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademiesRoute: typeof AcademiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AthletesRoute: typeof AthletesRoute
  BenefitsRoute: typeof BenefitsRoute
  BlackBeltsRoute: typeof BlackBeltsRouteWithChildren
  ChampionshipsRoute: typeof ChampionshipsRoute
  ContactRoute: typeof ContactRoute
  DiplomaRequestRoute: typeof DiplomaRequestRoute
  GraduatesRoute: typeof GraduatesRouteWithChildren
  MembersRoute: typeof MembersRoute
  MyCardRoute: typeof MyCardRoute
  MyCompetitionsRoute: typeof MyCompetitionsRoute
  MyPermitsRoute: typeof MyPermitsRoute
  MyProfileRoute: typeof MyProfileRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TypographyRoute: typeof TypographyRoute
  WelcomeRoute: typeof WelcomeRoute
  AcademyPermitRoute: typeof AcademyPermitRoute
  AthleteForgotPasswordRoute: typeof AthleteForgotPasswordRoute
  AthleteLoginRoute: typeof AthleteLoginRoute
  AthleteResetPasswordRoute: typeof AthleteResetPasswordRoute
  AthleteSignupRoute: typeof AthleteSignupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  MyPermitPermitNumberRoute: typeof MyPermitPermitNumberRoute
  NewsSlugRoute: typeof NewsSlugRoute
  RegisterAcademyRoute: typeof RegisterAcademyRoute
  RegisterAthleteRoute: typeof RegisterAthleteRoute
  VerifyAthleteIdRoute: typeof VerifyAthleteIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  RegisterEventEventIdRoute: typeof RegisterEventEventIdRoute
  VerifyAcademyPermitNumberRoute: typeof VerifyAcademyPermitNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-permits': {
      id: '/my-permits'
      path: '/my-permits'
      fullPath: '/my-permits'
      preLoaderRoute: typeof MyPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-competitions': {
      id: '/my-competitions'
      path: '/my-competitions'
      fullPath: '/my-competitions'
      preLoaderRoute: typeof MyCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-card': {
      id: '/my-card'
      path: '/my-card'
      fullPath: '/my-card'
      preLoaderRoute: typeof MyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates': {
      id: '/graduates'
      path: '/graduates'
      fullPath: '/graduates'
      preLoaderRoute: typeof GraduatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diploma-request': {
      id: '/diploma-request'
      path: '/diploma-request'
      fullPath: '/diploma-request'
      preLoaderRoute: typeof DiplomaRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championships': {
      id: '/championships'
      path: '/championships'
      fullPath: '/championships'
      preLoaderRoute: typeof ChampionshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-belts': {
      id: '/black-belts'
      path: '/black-belts'
      fullPath: '/black-belts'
      preLoaderRoute: typeof BlackBeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies': {
      id: '/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$athleteId': {
      id: '/verify/$athleteId'
      path: '/verify/$athleteId'
      fullPath: '/verify/$athleteId'
      preLoaderRoute: typeof VerifyAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/athlete': {
      id: '/register/athlete'
      path: '/register/athlete'
      fullPath: '/register/athlete'
      preLoaderRoute: typeof RegisterAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/academy': {
      id: '/register/academy'
      path: '/register/academy'
      fullPath: '/register/academy'
      preLoaderRoute: typeof RegisterAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-permit/$permitNumber': {
      id: '/my-permit/$permitNumber'
      path: '/my-permit/$permitNumber'
      fullPath: '/my-permit/$permitNumber'
      preLoaderRoute: typeof MyPermitPermitNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/$graduateId': {
      id: '/graduates/$graduateId'
      path: '/$graduateId'
      fullPath: '/graduates/$graduateId'
      preLoaderRoute: typeof GraduatesGraduateIdRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-belts/$id': {
      id: '/black-belts/$id'
      path: '/$id'
      fullPath: '/black-belts/$id'
      preLoaderRoute: typeof BlackBeltsIdRouteImport
      parentRoute: typeof BlackBeltsRoute
    }
    '/athlete/signup': {
      id: '/athlete/signup'
      path: '/athlete/signup'
      fullPath: '/athlete/signup'
      preLoaderRoute: typeof AthleteSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/reset-password': {
      id: '/athlete/reset-password'
      path: '/athlete/reset-password'
      fullPath: '/athlete/reset-password'
      preLoaderRoute: typeof AthleteResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/login': {
      id: '/athlete/login'
      path: '/athlete/login'
      fullPath: '/athlete/login'
      preLoaderRoute: typeof AthleteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/forgot-password': {
      id: '/athlete/forgot-password'
      path: '/athlete/forgot-password'
      fullPath: '/athlete/forgot-password'
      preLoaderRoute: typeof AthleteForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rankings': {
      id: '/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminRankingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permits': {
      id: '/admin/permits'
      path: '/permits'
      fullPath: '/admin/permits'
      preLoaderRoute: typeof AdminPermitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diploma-requests': {
      id: '/admin/diploma-requests'
      path: '/diploma-requests'
      fullPath: '/admin/diploma-requests'
      preLoaderRoute: typeof AdminDiplomaRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/black-belts': {
      id: '/admin/black-belts'
      path: '/black-belts'
      fullPath: '/admin/black-belts'
      preLoaderRoute: typeof AdminBlackBeltsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/benefits': {
      id: '/admin/benefits'
      path: '/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AdminBenefitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/athletes': {
      id: '/admin/athletes'
      path: '/athletes'
      fullPath: '/admin/athletes'
      preLoaderRoute: typeof AdminAthletesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academies': {
      id: '/admin/academies'
      path: '/academies'
      fullPath: '/admin/academies'
      preLoaderRoute: typeof AdminAcademiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academy/permit': {
      id: '/academy/permit'
      path: '/academy/permit'
      fullPath: '/academy/permit'
      preLoaderRoute: typeof AcademyPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/academy/$permitNumber': {
      id: '/verify/academy/$permitNumber'
      path: '/verify/academy/$permitNumber'
      fullPath: '/verify/academy/$permitNumber'
      preLoaderRoute: typeof VerifyAcademyPermitNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/event/$eventId': {
      id: '/register/event/$eventId'
      path: '/register/event/$eventId'
      fullPath: '/register/event/$eventId'
      preLoaderRoute: typeof RegisterEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcademiesRoute: typeof AdminAcademiesRoute
  AdminAthletesRoute: typeof AdminAthletesRoute
  AdminBenefitsRoute: typeof AdminBenefitsRoute
  AdminBlackBeltsRoute: typeof AdminBlackBeltsRoute
  AdminDiplomaRequestsRoute: typeof AdminDiplomaRequestsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPermitsRoute: typeof AdminPermitsRoute
  AdminRankingsRoute: typeof AdminRankingsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademiesRoute: AdminAcademiesRoute,
  AdminAthletesRoute: AdminAthletesRoute,
  AdminBenefitsRoute: AdminBenefitsRoute,
  AdminBlackBeltsRoute: AdminBlackBeltsRoute,
  AdminDiplomaRequestsRoute: AdminDiplomaRequestsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPermitsRoute: AdminPermitsRoute,
  AdminRankingsRoute: AdminRankingsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlackBeltsRouteChildren {
  BlackBeltsIdRoute: typeof BlackBeltsIdRoute
}

const BlackBeltsRouteChildren: BlackBeltsRouteChildren = {
  BlackBeltsIdRoute: BlackBeltsIdRoute,
}

const BlackBeltsRouteWithChildren = BlackBeltsRoute._addFileChildren(
  BlackBeltsRouteChildren,
)

interface GraduatesRouteChildren {
  GraduatesGraduateIdRoute: typeof GraduatesGraduateIdRoute
}

const GraduatesRouteChildren: GraduatesRouteChildren = {
  GraduatesGraduateIdRoute: GraduatesGraduateIdRoute,
}

const GraduatesRouteWithChildren = GraduatesRoute._addFileChildren(
  GraduatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademiesRoute: AcademiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AthletesRoute: AthletesRoute,
  BenefitsRoute: BenefitsRoute,
  BlackBeltsRoute: BlackBeltsRouteWithChildren,
  ChampionshipsRoute: ChampionshipsRoute,
  ContactRoute: ContactRoute,
  DiplomaRequestRoute: DiplomaRequestRoute,
  GraduatesRoute: GraduatesRouteWithChildren,
  MembersRoute: MembersRoute,
  MyCardRoute: MyCardRoute,
  MyCompetitionsRoute: MyCompetitionsRoute,
  MyPermitsRoute: MyPermitsRoute,
  MyProfileRoute: MyProfileRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TypographyRoute: TypographyRoute,
  WelcomeRoute: WelcomeRoute,
  AcademyPermitRoute: AcademyPermitRoute,
  AthleteForgotPasswordRoute: AthleteForgotPasswordRoute,
  AthleteLoginRoute: AthleteLoginRoute,
  AthleteResetPasswordRoute: AthleteResetPasswordRoute,
  AthleteSignupRoute: AthleteSignupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  MyPermitPermitNumberRoute: MyPermitPermitNumberRoute,
  NewsSlugRoute: NewsSlugRoute,
  RegisterAcademyRoute: RegisterAcademyRoute,
  RegisterAthleteRoute: RegisterAthleteRoute,
  VerifyAthleteIdRoute: VerifyAthleteIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  RegisterEventEventIdRoute: RegisterEventEventIdRoute,
  VerifyAcademyPermitNumberRoute: VerifyAcademyPermitNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
