/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyCardRouteImport } from './routes/my-card'
import { Route as GraduatesRouteImport } from './routes/graduates'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ChampionshipsRouteImport } from './routes/championships'
import { Route as BlackBeltsRouteImport } from './routes/black-belts'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademiesRouteImport } from './routes/academies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyAthleteIdRouteImport } from './routes/verify.$athleteId'
import { Route as RegisterAthleteRouteImport } from './routes/register.athlete'
import { Route as RegisterAcademyRouteImport } from './routes/register.academy'
import { Route as GraduatesGraduateIdRouteImport } from './routes/graduates.$graduateId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminYoutubeRouteImport } from './routes/admin.youtube'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRankingsRouteImport } from './routes/admin.rankings'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminBlackBeltsRouteImport } from './routes/admin.black-belts'
import { Route as AdminAcademiesRouteImport } from './routes/admin.academies'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCardRoute = MyCardRouteImport.update({
  id: '/my-card',
  path: '/my-card',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesRoute = GraduatesRouteImport.update({
  id: '/graduates',
  path: '/graduates',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipsRoute = ChampionshipsRouteImport.update({
  id: '/championships',
  path: '/championships',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackBeltsRoute = BlackBeltsRouteImport.update({
  id: '/black-belts',
  path: '/black-belts',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesRoute = AcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyAthleteIdRoute = VerifyAthleteIdRouteImport.update({
  id: '/verify/$athleteId',
  path: '/verify/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAthleteRoute = RegisterAthleteRouteImport.update({
  id: '/register/athlete',
  path: '/register/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAcademyRoute = RegisterAcademyRouteImport.update({
  id: '/register/academy',
  path: '/register/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesGraduateIdRoute = GraduatesGraduateIdRouteImport.update({
  id: '/$graduateId',
  path: '/$graduateId',
  getParentRoute: () => GraduatesRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingsRoute = AdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlackBeltsRoute = AdminBlackBeltsRouteImport.update({
  id: '/black-belts',
  path: '/black-belts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademiesRoute = AdminAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/athletes': typeof AthletesRoute
  '/black-belts': typeof BlackBeltsRoute
  '/championships': typeof ChampionshipsRoute
  '/events': typeof EventsRouteWithChildren
  '/graduates': typeof GraduatesRouteWithChildren
  '/my-card': typeof MyCardRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/typography': typeof TypographyRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/athletes': typeof AthletesRoute
  '/black-belts': typeof BlackBeltsRoute
  '/championships': typeof ChampionshipsRoute
  '/events': typeof EventsRouteWithChildren
  '/graduates': typeof GraduatesRouteWithChildren
  '/my-card': typeof MyCardRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/typography': typeof TypographyRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academies': typeof AcademiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/athletes': typeof AthletesRoute
  '/black-belts': typeof BlackBeltsRoute
  '/championships': typeof ChampionshipsRoute
  '/events': typeof EventsRouteWithChildren
  '/graduates': typeof GraduatesRouteWithChildren
  '/my-card': typeof MyCardRoute
  '/news': typeof NewsRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/typography': typeof TypographyRoute
  '/admin/academies': typeof AdminAcademiesRoute
  '/admin/black-belts': typeof AdminBlackBeltsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/graduates/$graduateId': typeof GraduatesGraduateIdRoute
  '/register/academy': typeof RegisterAcademyRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/verify/$athleteId': typeof VerifyAthleteIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academies'
    | '/admin'
    | '/athletes'
    | '/black-belts'
    | '/championships'
    | '/events'
    | '/graduates'
    | '/my-card'
    | '/news'
    | '/rankings'
    | '/rules'
    | '/typography'
    | '/admin/academies'
    | '/admin/black-belts'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/rankings'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academies'
    | '/athletes'
    | '/black-belts'
    | '/championships'
    | '/events'
    | '/graduates'
    | '/my-card'
    | '/news'
    | '/rankings'
    | '/rules'
    | '/typography'
    | '/admin/academies'
    | '/admin/black-belts'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/rankings'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academies'
    | '/admin'
    | '/athletes'
    | '/black-belts'
    | '/championships'
    | '/events'
    | '/graduates'
    | '/my-card'
    | '/news'
    | '/rankings'
    | '/rules'
    | '/typography'
    | '/admin/academies'
    | '/admin/black-belts'
    | '/admin/events'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/news'
    | '/admin/rankings'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/youtube'
    | '/events/$eventId'
    | '/graduates/$graduateId'
    | '/register/academy'
    | '/register/athlete'
    | '/verify/$athleteId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademiesRoute: typeof AcademiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AthletesRoute: typeof AthletesRoute
  BlackBeltsRoute: typeof BlackBeltsRoute
  ChampionshipsRoute: typeof ChampionshipsRoute
  EventsRoute: typeof EventsRouteWithChildren
  GraduatesRoute: typeof GraduatesRouteWithChildren
  MyCardRoute: typeof MyCardRoute
  NewsRoute: typeof NewsRoute
  RankingsRoute: typeof RankingsRoute
  RulesRoute: typeof RulesRoute
  TypographyRoute: typeof TypographyRoute
  RegisterAcademyRoute: typeof RegisterAcademyRoute
  RegisterAthleteRoute: typeof RegisterAthleteRoute
  VerifyAthleteIdRoute: typeof VerifyAthleteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-card': {
      id: '/my-card'
      path: '/my-card'
      fullPath: '/my-card'
      preLoaderRoute: typeof MyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates': {
      id: '/graduates'
      path: '/graduates'
      fullPath: '/graduates'
      preLoaderRoute: typeof GraduatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championships': {
      id: '/championships'
      path: '/championships'
      fullPath: '/championships'
      preLoaderRoute: typeof ChampionshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-belts': {
      id: '/black-belts'
      path: '/black-belts'
      fullPath: '/black-belts'
      preLoaderRoute: typeof BlackBeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies': {
      id: '/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$athleteId': {
      id: '/verify/$athleteId'
      path: '/verify/$athleteId'
      fullPath: '/verify/$athleteId'
      preLoaderRoute: typeof VerifyAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/athlete': {
      id: '/register/athlete'
      path: '/register/athlete'
      fullPath: '/register/athlete'
      preLoaderRoute: typeof RegisterAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/academy': {
      id: '/register/academy'
      path: '/register/academy'
      fullPath: '/register/academy'
      preLoaderRoute: typeof RegisterAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates/$graduateId': {
      id: '/graduates/$graduateId'
      path: '/$graduateId'
      fullPath: '/graduates/$graduateId'
      preLoaderRoute: typeof GraduatesGraduateIdRouteImport
      parentRoute: typeof GraduatesRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rankings': {
      id: '/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminRankingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/black-belts': {
      id: '/admin/black-belts'
      path: '/black-belts'
      fullPath: '/admin/black-belts'
      preLoaderRoute: typeof AdminBlackBeltsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academies': {
      id: '/admin/academies'
      path: '/academies'
      fullPath: '/admin/academies'
      preLoaderRoute: typeof AdminAcademiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademiesRoute: typeof AdminAcademiesRoute
  AdminBlackBeltsRoute: typeof AdminBlackBeltsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminRankingsRoute: typeof AdminRankingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademiesRoute: AdminAcademiesRoute,
  AdminBlackBeltsRoute: AdminBlackBeltsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminRankingsRoute: AdminRankingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GraduatesRouteChildren {
  GraduatesGraduateIdRoute: typeof GraduatesGraduateIdRoute
}

const GraduatesRouteChildren: GraduatesRouteChildren = {
  GraduatesGraduateIdRoute: GraduatesGraduateIdRoute,
}

const GraduatesRouteWithChildren = GraduatesRoute._addFileChildren(
  GraduatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademiesRoute: AcademiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AthletesRoute: AthletesRoute,
  BlackBeltsRoute: BlackBeltsRoute,
  ChampionshipsRoute: ChampionshipsRoute,
  EventsRoute: EventsRouteWithChildren,
  GraduatesRoute: GraduatesRouteWithChildren,
  MyCardRoute: MyCardRoute,
  NewsRoute: NewsRoute,
  RankingsRoute: RankingsRoute,
  RulesRoute: RulesRoute,
  TypographyRoute: TypographyRoute,
  RegisterAcademyRoute: RegisterAcademyRoute,
  RegisterAthleteRoute: RegisterAthleteRoute,
  VerifyAthleteIdRoute: VerifyAthleteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
